### ISSUE TITLE
Supervisor fails when preloaded device moves to a different app

### ISSUE THREAD

**Issue by roman-mazur** [balena-io/balena-supervisor#1105]
After a device with preloaded containers is moved to a different app before it boots, the supervisor fails with the following log:
```
Oct 01 17:00:11 b928ea6 resin-supervisor[1792]: Event: Device bootstrap {}
Oct 01 17:00:11 b928ea6 resin-supervisor[1792]: Attempting to pin device to preloaded release...
Oct 01 17:00:12 b928ea6 resin-supervisor[1792]: Could not pin device to release!
Oct 01 17:00:12 b928ea6 resin-supervisor[1792]: Error:  Error: Cannot continue pinning preloaded device! No release found!
Oct 01 17:00:12 b928ea6 resin-supervisor[1792]:     at e.<anonymous> (/usr/src/app/dist/app.js:409:25954)
Oct 01 17:00:12 b928ea6 resin-supervisor[1792]:     at /usr/src/app/dist/app.js:409:13720
Oct 01 17:00:12 b928ea6 resin-supervisor[1792]:     at Object.next (/usr/src/app/dist/app.js:409:13825)
Oct 01 17:00:12 b928ea6 resin-supervisor[1792]:     at a (/usr/src/app/dist/app.js:409:12571)
Oct 01 17:00:12 b928ea6 resin-supervisor[1792]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Oct 01 17:00:12 b928ea6 resin-supervisor[1792]: Event: Device bootstrap failed, retrying {"delay":30000,"error":{"message":"Cannot continue pinning preloaded device! No release found!","stack":"Error: Cannot cont>
```

Workaround included:
- re-pinning devices to correct application releases on the backend using the SDK
- clearing local device state data to make supervisor fetch new correct state from the backend (deleting `/mnt/data/apps.json`, the database, and restarting the supervisor)

**Comment by CameronDiver** [comment]
I've clarified a little bit, this problem exists because the supervisor attempts to pin itself to the previous application after being moved.

**Comment by roman-mazur** [comment]
@CameronDiver should we track the cloud API issue separately? After devices were moved to a different app, they still referred to the previous app releases.

**Comment by CameronDiver** [comment]
I'm not 100% on what you mean @roman-mazur ? Which specific cloud issue?

**Comment by roman-mazur** [comment]
@CameronDiver after moving a device from one application to another, the device release pins were referring to a release from the old app - this sounds like a bug in the API impl.
We had to "re-pin" the devices first, and then clean the supervisor state to make it fetch new releases info.

**Comment by CameronDiver** [comment]
This doesn't really seem like an API issue. The supervisor has to specify a release ID when pinning a device, if that release ID is wrong, then there's nothing really the API can do.
