### ISSUE TITLE
Supervisor fails with `readlink /var/lib/docker/overlay2: invalid argument`

### ISSUE THREAD

**Issue by xginn8** [balena-io/balena-supervisor#1143]
The supervisor fails to start with the following errors on a custom TX2:

```
[2019-11-14T23:49:06.273Z] Unhandled rejection Error: (HTTP code 500) server error - readlink /var/lib/docker/overlay2: invalid argument 
    at /usr/src/app/dist/app.js:576:112035
    at /usr/src/app/dist/app.js:576:111998
    at m.buildPayload (/usr/src/app/dist/app.js:576:112008)
    at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:576:111508)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by xginn8** [comment]
This issue was fixed by performing a docker cleanup.

**Comment by robertgzr** [comment]
Seems to be connected to https://github.com/moby/moby/issues/35747, which is more likely when large container images are used.

**Comment by roman-mazur** [comment]
The investigation of the engine problem will be done in the context of https://github.com/balena-os/balena-engine/issues/197. We are going to prepare a setup to simulate the usage of big images and research the engine behaviour.

@CameronDiver the only thing in the context of this supervisor ticket that makes sense to do, I think, is to improve this error reporting. The error we see in the report is produced by the supervisor node process and leads to a crash, but it's absolutely unclear where it originates from, at what stage it's raised.
