### ISSUE TITLE
add better support for faster testing

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-supervisor#1278]
I might be misunderstanding the available scripts in the package.json so let me know if I missed something and I'll be sure to then create a PR for the README with the information I missed so others can see it too.

I need a way to quickly run tests for single spec files but could not find a way to do that. This can save a lot of time when developing.

**Comment by 20k-ultra** [comment]
I've added this script to my package.json while working on another issue and it was worked well for me. 

```
"test:grep": "npm run test:build && TEST=1 mocha --opts test/fast-mocha.opts --grep"
```

I would use it like:

```
npm run test:grep authentication
# OR
npm run test:grep "detect a V2 delta"
```

Thoughts on me making a PR with this new script ?

**Comment by CameronDiver** [comment]
@20k-ultra building it on top of `test:fast` probably makes more sense, given this is a way to iterate more quickly. `test:fast` just use ts-node instead of having a separate compile step. 

In addition, you can pass these args to the script directly:
```
➜  balena-supervisor git:(1249-support-bearer-token-header) npm run test:fast -- --grep authentication    

> balena-supervisor@11.1.9 test:fast /home/cameron/balena/modules/balena-supervisor
> TEST=1 mocha --opts test/fast-mocha.opts "--grep" "authentication"



  SupervisorAPI authentication
[error]   Error on switching supervisor API listening rules - stopping API.
[error]      Error: Command failed: ip6tables -A INPUT -p tcp --dport 48484 -j DROP
[error]   Fatal: can't open lock file /run/xtables.lock: Permission denied
[error]   
[error]       at ChildProcess.exithandler (child_process.js:303:12)
[error]       at ChildProcess.emit (events.js:311:20)
[error]       at maybeClose (internal/child_process.js:1021:16)
[error]       at Socket.<anonymous> (internal/child_process.js:443:11)
[error]       at Socket.emit (events.js:311:20)
[error]       at Pipe.<anonymous> (net.js:668:12)
[error]   
[api]     POST /v1/blink 401 - 7.376 ms
    ✓ finds no apiKey and rejects
[event]   Event: Device blink {}
[api]     POST /v1/blink 200 - 3.078 ms
    ✓ finds apiKey from query
[event]   Event: Device blink {}
[api]     POST /v1/blink 200 - 1.676 ms
    ✓ finds apiKey from Authorization header (ApiKey scheme)
[event]   Event: Device blink {}
[api]     POST /v1/blink 200 - 1.332 ms
    ✓ finds apiKey from Authorization header (Bearer scheme)
[api]     POST /v1/blink 401 - 1.131 ms
    ✓ rejects invalid apiKey from query
[api]     POST /v1/blink 401 - 1.170 ms
    ✓ rejects invalid apiKey from Authorization header (ApiKey scheme)
[api]     POST /v1/blink 401 - 1.226 ms
    ✓ rejects invalid apiKey from Authorization header (Bearer scheme)


  7 passing (194ms)
```

so I'd much rather not make the scripts section more complicated than it is.

**Comment by 20k-ultra** [comment]
I did see test:fast but for some reason that I couldn't pass in the grep flag. That works perfect and much faster then my script.
