### ISSUE TITLE
V1 API cannot start or stop valid appId

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-supervisor#1299]
The following response shows I have an application with appId value of 1.

```sh
curl -X GET --header "Content-Type:application/json" \
    "$BALENA_SUPERVISOR_ADDRESS/v1/apps/1?apikey=$BALENA_SUPERVISOR_API_KEY" 
{"appId":1,"containerId":"ada1133473b07b36cfce6c9b9577dd54ad281f022197b0a74850e53f61d982c2","env":{},"releaseId":1,"commit":"localrelease"}
```

Now when I try to stop or start this application using the V1 api I get an error

```sh
curl -X POST --header "Content-Type:application/json" \
    "$BALENA_SUPERVISOR_ADDRESS/v1/apps/1/stop?apikey=$BALENA_SUPERVISOR_API_KEY"                                       
{"status":"failed","message":"Cannot read property 'services' of undefined"}
```

Here is a log from the supervisor

```sh
error]   Error on POST /v1/apps/1/start:  TypeError: Cannot read property 'services' of undefined
[error]         at /usr/src/app/dist/app.js:14:1786162
[error]       at tryCatcher (/usr/src/app/dist/app.js:2:227165)
[error]       at Promise._settlePromiseFromHandler (/usr/src/app/dist/app.js:2:1652896)
[error]       at Promise._settlePromise (/usr/src/app/dist/app.js:2:1654179)
[error]       at Promise._settlePromise0 (/usr/src/app/dist/app.js:2:1655219)
[error]       at Promise._settlePromises (/usr/src/app/dist/app.js:2:1656927)
[error]       at Promise._fulfill (/usr/src/app/dist/app.js:2:1655715)
[error]       at Promise._resolveCallback (/usr/src/app/dist/app.js:2:1651079)
[error]       at Promise._settlePromiseFromHandler (/usr/src/app/dist/app.js:2:1653155)
[error]       at Promise._settlePromise (/usr/src/app/dist/app.js:2:1654179)
[error]       at Promise._settlePromise0 (/usr/src/app/dist/app.js:2:1655219)
[error]       at Promise._settlePromises (/usr/src/app/dist/app.js:2:1656927)
[error]       at Promise._fulfill (/usr/src/app/dist/app.js:2:1655715)
[error]       at Promise._resolveCallback (/usr/src/app/dist/app.js:2:1651079)
[error]       at Holder$4._callFunction (eval at generateHolderClass (/usr/src/app/dist/app.js:2:1709070), <anonymous>:17:29)
[error]       at Holder$4.checkFulfillment (eval at generateHolderClass (/usr/src/app/dist/app.js:2:1709070), <anonymous>:27:30)
[error]       at Promise.eval (eval at thenCallback (/usr/src/app/dist/app.js:2:1704551), <anonymous>:4:20)
[error]       at Promise._settlePromise (/usr/src/app/dist/app.js:2:1654246)
[error]       at Promise._settlePromise0 (/usr/src/app/dist/app.js:2:1655219)
[error]       at Promise._settlePromises (/usr/src/app/dist/app.js:2:1656927)
[error]       at _drainQueueStep (/usr/src/app/dist/app.js:2:1659861)
[error]       at _drainQueue (/usr/src/app/dist/app.js:2:1659757)
[api]     POST /v1/apps/1/start 503 - 33.648 ms
```

test on supervisor version 11.2.0 but this might exist in older versions as well.

**Comment by CameronDiver** [comment]
Please can you update the supervisor version in your issue with the correct version, I'm fairly sure you didn't test on the 5-6 years old v1.22 supervisor :P

**Comment by nitishagar** [comment]
@20k-ultra @CameronDiver I am fairly new to the codebase. But making some local changes and trying out APIs. I think the issue is double `app` key: https://github.com/balena-io/balena-supervisor/blob/master/src/device-api/v1.js#L31 

Any way you can help me test out this change?

**Comment by CameronDiver** [comment]
@nitishagar you should be able to run the commands which @20k-ultra added above to check the results.

**Comment by nitishagar** [comment]
The test replicates this exact condition with the following error without the `v1.js` fix. Error excerpt below:

```
[error]   Error on POST /v1/apps/2/stop:  TypeError: Cannot read property 'services' of undefined
[error]         at /Users/nitish/repos/balena-supervisor/build/src/device-api/v1.js:34:83
[error]       at tryCatcher (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/util.js:16:23)
[error]       at Promise._settlePromiseFromHandler (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:547:31)
[error]       at Promise._settlePromise (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:604:18)
[error]       at Promise._settlePromise0 (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:649:10)
[error]       at Promise._settlePromises (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:729:18)
[error]       at Promise._fulfill (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:673:18)
[error]       at Promise._resolveCallback (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:466:57)
[error]       at Promise._settlePromiseFromHandler (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:559:17)
[error]       at Promise._settlePromise (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:604:18)
[error]       at Promise._settlePromise0 (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:649:10)
[error]       at Promise._settlePromises (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:729:18)
[error]       at Promise._fulfill (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:673:18)
[error]       at Promise._resolveCallback (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:466:57)
[error]       at Holder$4._callFunction (eval at generateHolderClass (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/join.js:91:16), <anonymous>:17:29)
[error]       at Holder$4.checkFulfillment (eval at generateHolderClass (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/join.js:91:16), <anonymous>:27:30)
[error]       at Promise.eval (eval at thenCallback (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/join.js:13:16), <anonymous>:4:20)
[error]       at Promise._settlePromise (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:601:21)
[error]       at Promise._settlePromise0 (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:649:10)
[error]       at Promise._settlePromises (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/promise.js:729:18)
[error]       at _drainQueueStep (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/async.js:93:12)
[error]       at _drainQueue (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/async.js:86:9)
[error]       at Async._drainQueues (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/async.js:102:5)
[error]       at Immediate.Async.drainQueues [as _onImmediate] (/Users/nitish/repos/balena-supervisor/node_modules/bluebird/js/release/async.js:15:14)
[error]       at processImmediate (internal/timers.js:456:21)
```
