### ISSUE TITLE
Error reporting initial configuration, will retry t

### ISSUE THREAD

**Issue by bartversluijs** [balena-io/balena-supervisor#1308]
Hi all,

I've created a openBalena dev server to check out openBalena. I've created an app on that server for the raspberry pi 4, and configured the image file of the RPI 4 to my openBalena dev server. I've flashed the image on an SD card and booted the RPI 4. So far so good.

But after some time, the Raspberry Pi 4 still showed it wasn't online. So I ssh'd into the RPI 4 and checked out the supervisor container logs. The following error came up a few times:
```
Error reporting initial configuration, will retry t
[error]         at /usr/src/app/dist/app.js:484:8806
[error]       at c (/usr/src/app/dist/app.js:9:77566)
[error]       at O._settlePromiseFromHandler (/usr/src/app/dist/app.js:312:325515)
[error]       at O._settlePromise (/usr/src/app/dist/app.js:312:326315)
[error]       at O._settlePromise0 (/usr/src/app/dist/app.js:312:327014)
[error]       at O._settlePromises (/usr/src/app/dist/app.js:312:328366)
[error]       at O._fulfill (/usr/src/app/dist/app.js:312:327384)
[error]       at q._callback (/usr/src/app/dist/app.js:122:15684)
[error]       at q.t._callback.t.callback.t.callback (/usr/src/app/dist/app.js:544:5327)
[error]       at q.emit (events.js:189:13)
[error]       at q.<anonymous> (/usr/src/app/dist/app.js:544:18140)
[error]       at q.emit (events.js:189:13)
[error]       at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:544:16982)
[error]       at Object.onceWrapper (events.js:277:13)
[error]       at IncomingMessage.emit (events.js:194:15)
[error]       at endReadableNT (_stream_readable.js:1125:12)
[error]       at process._tickCallback (internal/process/next_tick.js:63:19)
```

After some time (like 5 minutes), the RPI 4 showed as online on the openBalena server and the supervisor had the following logs:
```
[api]     GET /v1/healthy 200 - 16.967 ms
[debug]   Starting current state report
[debug]   Starting target state poll
[info]    Applying target state
[event]   Event: Apply config change in progress {}
[event]   Event: Apply config change success {}
[event]   Event: Network creation {}
[debug]   Finished applying target state
[success] Device state apply success
[info]    Internet Connectivity: OK
```

So it works. But I thought it's worth mentioning that those errors occured.

On a side note, maybe it's useful to add timestamp to the logs?

**Comment by bartversluijs** [comment]
After checking the supervisor logs again, this error was also shown after the `Internet Connectivity: OK`:
```
[error]   LogBackend: server responded with status code: 504
```

Maybe it's nothing, but I'd like to give as much information as possible.

**Comment by CameronDiver** [comment]
@bartversluijs thanks for the report! What was the supervisor version that you noticed this with? There was a fix semi-recently related to this, where the supervisor would try to log with an uninitialized API key, and the API would cache the permissions of this key, even after it was registered. 

The fix was released in [v10.6.34](https://github.com/balena-io/balena-supervisor/blob/master/CHANGELOG.md#v10634)

**Comment by bartversluijs** [comment]
Hi @CameronDiver,

The problem occured on a Raspberry Pi 4 with BalenaOS 2.48.0 (not sure about the revision tbh) and supervisor version 10.8.0

**Comment by CameronDiver** [comment]
Hmm so it seems my changes do not actually give more information about this specific error unfortunately. I'll look at other methods of extracting more information.
