### ISSUE TITLE
Restarting device from dashboard gets 503 error from supervisor: 

### ISSUE THREAD

**Issue by saintaardvark** [balena-io/balena-supervisor#1398]
A forum user has reported that they are unable to use the "Restart" button on the dashboard on at least one of their devices; they get an error message in the dashboard saying `Request error: [object Object]`.  The device has been shared with support, and I've confirmed this behaviour.  

When I try to use the "Restart" button, I see this show up in the supervisor logs from the device:

```
[event]   Event: Restart container (v1) {"appId":[xxx]}
[error]   Device state apply error TypeError: Cannot read property 'ipam' of undefined
[error]         at Network.isEqualConfig (/usr/src/app/dist/app.js:2:960631)
[error]       at /usr/src/app/dist/app.js:22:13749
[error]       at arrayFilter (/usr/src/app/dist/app.js:2:86532)
[error]       at Function.lodash.filter (/usr/src/app/dist/app.js:2:175795)
[error]       at ApplicationManager._compareNetworksOrVolumesForUpdate (/usr/src/app/dist/app.js:22:13680)
[error]       at ApplicationManager.compareNetworksForUpdate (/usr/src/app/dist/app.js:22:13959)
[error]       at ApplicationManager._nextStepsForAppUpdate (/usr/src/app/dist/app.js:22:20489)
[error]       at /usr/src/app/dist/app.js:22:27294
[error]       at tryCatcher (/usr/src/app/dist/app.js:2:223577)
[error]       at Function.Promise.attempt.Promise.try (/usr/src/app/dist/app.js:6:70875)
[error]       at ApplicationManager._inferNextSteps (/usr/src/app/dist/app.js:22:26251)
[error]       at ApplicationManager.getRequiredSteps (/usr/src/app/dist/app.js:22:30834)
[error]       at /usr/src/app/dist/app.js:10:7618
[info]    Applying target state
[error]   Error on POST /v1/restart:  TypeError: Cannot read property 'ipam' of undefined
[error]         at Network.isEqualConfig (/usr/src/app/dist/app.js:2:960631)
[error]       at /usr/src/app/dist/app.js:22:13749
[error]       at arrayFilter (/usr/src/app/dist/app.js:2:86532)
[error]       at Function.lodash.filter (/usr/src/app/dist/app.js:2:175795)
[error]       at ApplicationManager._compareNetworksOrVolumesForUpdate (/usr/src/app/dist/app.js:22:13680)
[error]       at ApplicationManager.compareNetworksForUpdate (/usr/src/app/dist/app.js:22:13959)
[error]       at ApplicationManager._nextStepsForAppUpdate (/usr/src/app/dist/app.js:22:20489)
[error]       at /usr/src/app/dist/app.js:22:27294
[error]       at tryCatcher (/usr/src/app/dist/app.js:2:223577)
[error]       at Function.Promise.attempt.Promise.try (/usr/src/app/dist/app.js:6:70875)
[error]       at ApplicationManager._inferNextSteps (/usr/src/app/dist/app.js:22:26251)
[error]       at ApplicationManager.getRequiredSteps (/usr/src/app/dist/app.js:22:30834)
[error]       at /usr/src/app/dist/app.js:10:7618
```

The user's supervisor version is 11.9.4, and the hostOS is balenaOS 2.52.7+rev1 (prod version).  Device checks are green on the device.

I've double-checked this on one of my own devices; another support agent was able to restart services on it without any problems.  That device is running supervisor version 10.6.27, balenaOS 2.47.0+rev1.

**Comment by richbayliss** [comment]
I can confirm this on a Raspberry Pi 3B+ I just upgraded.
