### ISSUE TITLE
`No delay specified in scheduledApply` error while livepushing

### ISSUE THREAD

**Issue by xginn8** [balena-io/balena-supervisor#1428]
```
[Debug]   Sending request to http://192.168.3.215:48484/v2/local/target-state
No delay specified in scheduledApply

BadRequestDeviceAPIError: No delay specified in scheduledApply
    at Request._callback (/usr/lib/node_modules/balena-cli/build/utils/device/api.js:145:39)
    at Request.self.callback (/usr/lib/node_modules/balena-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

ref. https://www.flowdock.com/app/rulemotion/r-supervisor/threads/ZrRWOyEHrSg39e-xEyvZVOUN57b

supervisor `v11.11.7`
balena-CLI `12.12.1`

**Comment by Timple** [comment]
Having the same issue. Did you get around this?

**Comment by 20k-ultra** [comment]
hey @xginn8 and @Timple, could you provide more info on when this happens ? I'm hoping to get some reproducible steps or at least a better idea of what I can do to trigger this to happen. Should I be triggering restarts on my service or does this just happen without any input from you ? What is the frequency in which this happens ? 

So far, running Supervisor `v11.14.0` and CLI `12.20.0` hasn't given me the issue but I haven't messed around with it much.

**Comment by Timple** [comment]
Yesterday it reproduced fine. I'll try to reproduce today. Maybe it's related to this error I was also constantly getting when doing a local push:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: No native build was found for platform=linux arch=x64 runtime=node abi=64 uv=1 libc=glibc node=10.21.0
    loaded from: /home/tim/.local/bin/ref-napi

    at Function.load.path (/snapshot/versioned-source/node_modules/node-gyp-build/index.js:62:9)
    at load (/snapshot/versioned-source/node_modules/node-gyp-build/index.js:21:30)
    at Object.<anonymous> (/snapshot/versioned-source/node_modules/ref-napi/lib/ref.js:8:53)
    at Module._compile (pkg/prelude/bootstrap.js:1325:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1230:31)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/snapshot/versioned-source/node_modules/net-keepalive/lib/index.js:24:9)
    at Module._compile (pkg/prelude/bootstrap.js:1325:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
[Live]    Waiting for device state to settle...
[Live]    Device state settled
```

Anyway the workflow was that I was trying to push a large (1Gb+) image to a local balena instance (put in local mode).

CLI `12.20.0`, Supervisor `11.12.4` (PS. How do I get to the `11.14`? I cannot upgrade from the website: "restless-bird
BalenaOS v2.54.2")

**Comment by 20k-ultra** [comment]
There's currently no way officially supported way to upgrade the Supervisor version on the device other then upgrading the host OS that has the Supervisor version you want. `11.14.0` has rolled out into some production images so maybe your device hasn't gotten it yet. Your version is pretty new though so it won't resolve this issue.

So to confirm you're making changes which causes livepush to reload your service right and eventually this error will occur ? It is possible this is a bug in https://github.com/balena-io-modules/livepush that isn't providing something to the device it is suppose to so I am considering that too.

**Comment by 20k-ultra** [comment]
I have a device I've used for developing a lot so it's not clear what the conditions are but I'm not using livepush and I am getting am similar error:
```
Failed to get target state for device: InternalInconsistencyError: No delay specified in scheduledApply
```

My device has used livepush and currently running a custom tagged version of the Supervisor. This error is always logged when I deploy a new release and my device is currently not moving to the correct release (stuck on wrong release).
