### ISSUE TITLE
/v1/restart throws 503 and downloads release again

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-supervisor#1509]
Provisioned a RPI4 which has the latest versions in production as of writing this issue which are:

**Versions:**

Host OS version: balenaOS 2.58.6+rev1 (development)
Supervisor version: 12.1.4

**Steps to reproduce:**

1. Freshly provisioned device with a release (mine is a multi-container release with 3 services)
2. Click the restart button on the dashboard
3. See a toaster message (red bar with Request Error text) on the dashboard and can view errors in Supervisor journal logs.

 When looking at the journal logs I see a lot of issues.

1. My release was removed then downloaded again (the dashboard shows download progress as well)
2. Why do the steps contain fetch related steps and what is undefined ?
3. The log at the end says device state apply success and "Device state apply error Error" in the same second

```
Nov 03 19:05:29 13b8587 resin-supervisor[5200]: [event]   Event: Restart container (v1) {"appId":1658654}
Nov 03 19:05:29 13b8587 resin-supervisor[5200]: [event]   Event: Service kill {"service":{"appId":1658654,"serviceId":640680,"serviceName":"frontend","releaseId":1581185}}
Nov 03 19:05:29 13b8587 resin-supervisor[5200]: [event]   Event: Service kill {"service":{"appId":1658654,"serviceId":640681,"serviceName":"proxy","releaseId":1581185}}
Nov 03 19:05:29 13b8587 resin-supervisor[5200]: [event]   Event: Service kill {"service":{"appId":1658654,"serviceId":640682,"serviceName":"data","releaseId":1581185}}
Nov 03 19:05:30 13b8587 resin-supervisor[5200]: [event]   Event: Service exit {"service":{"appId":1658654,"serviceId":640680,"serviceName":"frontend","releaseId":1581185}}
Nov 03 19:05:30 13b8587 resin-supervisor[5200]: [event]   Event: Service stop {"service":{"appId":1658654,"serviceId":640680,"serviceName":"frontend","releaseId":1581185}}
Nov 03 19:05:31 13b8587 resin-supervisor[5200]: [event]   Event: Service exit {"service":{"appId":1658654,"serviceId":640682,"serviceName":"data","releaseId":1581185}}
Nov 03 19:05:31 13b8587 resin-supervisor[5200]: [event]   Event: Service exit {"service":{"appId":1658654,"serviceId":640681,"serviceName":"proxy","releaseId":1581185}}
Nov 03 19:05:31 13b8587 resin-supervisor[5200]: [event]   Event: Service stop {"service":{"appId":1658654,"serviceId":640682,"serviceName":"data","releaseId":1581185}}
Nov 03 19:05:31 13b8587 resin-supervisor[5200]: [event]   Event: Service stop {"service":{"appId":1658654,"serviceId":640681,"serviceName":"proxy","releaseId":1581185}}
Nov 03 19:05:32 13b8587 resin-supervisor[5200]: [event]   Event: Image removal {"image":{"id":4,"name":"registry2.balena-cloud.com/v2/7abcc0bc2042ae3f33ce8382989d6125@sha256:e2e87a8139b8fc14510095b210ad652d7d5badcc64fdc686cbf749d399fba15e","appId":1658654,"serviceId":640681,"serviceName":"proxy","imageId":2885966,"releaseId":1581185,"dependent":0,"dockerImageId":"sha256:4502983d72e2c72bc292effad1b15b49576da3801356f47fd275ba274d409c1a"}}
Nov 03 19:05:32 13b8587 resin-supervisor[5200]: [event]   Event: Image removal {"image":{"id":5,"name":"registry2.balena-cloud.com/v2/96085a3e3b54c7c63828b7ab51131652@sha256:e3a036b5232b6662ada12e52db3d162c54955190da793fc72d8db5c56d9d7828","appId":1658654,"serviceId":640680,"serviceName":"frontend","imageId":2885965,"releaseId":1581185,"dependent":0,"dockerImageId":"sha256:6091535294eb90c0e4d9bc9286095f73d9ad73a86df7456339456f7804c39d77"}}
Nov 03 19:05:32 13b8587 resin-supervisor[5200]: [event]   Event: Image removal {"image":{"id":6,"name":"registry2.balena-cloud.com/v2/441461dd470cb49e0a2435a19236067c@sha256:95d8fdae699b6cc8549921dc66934a67e64a8e5731fb65582214854d4008fd57","appId":1658654,"serviceId":640682,"serviceName":"data","imageId":2885967,"releaseId":1581185,"dependent":0,"dockerImageId":"sha256:ce18e1f9fbfd627a69b190f07aeac252856d63189e0d7f40f21ac55f9abb198a"}}
Nov 03 19:05:32 13b8587 resin-supervisor[5200]: [event]   Event: Image removed {"image":{"id":4,"name":"registry2.balena-cloud.com/v2/7abcc0bc2042ae3f33ce8382989d6125@sha256:e2e87a8139b8fc14510095b210ad652d7d5badcc64fdc686cbf749d399fba15e","appId":1658654,"serviceId":640681,"serviceName":"proxy","imageId":2885966,"releaseId":1581185,"dependent":0,"dockerImageId":"sha256:4502983d72e2c72bc292effad1b15b49576da3801356f47fd275ba274d409c1a"}}
Nov 03 19:05:32 13b8587 resin-supervisor[5200]: [event]   Event: Image removed {"image":{"id":5,"name":"registry2.balena-cloud.com/v2/96085a3e3b54c7c63828b7ab51131652@sha256:e3a036b5232b6662ada12e52db3d162c54955190da793fc72d8db5c56d9d7828","appId":1658654,"serviceId":640680,"serviceName":"frontend","imageId":2885965,"releaseId":1581185,"dependent":0,"dockerImageId":"sha256:6091535294eb90c0e4d9bc9286095f73d9ad73a86df7456339456f7804c39d77"}}
Nov 03 19:05:32 13b8587 resin-supervisor[5200]: [event]   Event: Image removed {"image":{"id":6,"name":"registry2.balena-cloud.com/v2/441461dd470cb49e0a2435a19236067c@sha256:95d8fdae699b6cc8549921dc66934a67e64a8e5731fb65582214854d4008fd57","appId":1658654,"serviceId":640682,"serviceName":"data","imageId":2885967,"releaseId":1581185,"dependent":0,"dockerImageId":"sha256:ce18e1f9fbfd627a69b190f07aeac252856d63189e0d7f40f21ac55f9abb198a"}}
Nov 03 19:05:34 13b8587 resin-supervisor[5200]: [success] Device state apply success
Nov 03 19:05:34 13b8587 resin-supervisor[5200]: [error]   Device state apply error Error: Failed to apply state transition steps. Cannot read property 'match' of undefined Steps:["fetch","fetch","fetch"]
Nov 03 19:05:34 13b8587 resin-supervisor[5200]: [error]         at /usr/src/app/src/device-state.ts:808:10
Nov 03 19:05:34 13b8587 resin-supervisor[5200]: [info]    Applying target state
Nov 03 19:05:34 13b8587 resin-supervisor[5200]: [error]   Error on POST /v1/restart:  Error: Failed to apply state transition steps. Cannot read property 'match' of undefined Steps:["fetch","fetch","fetch"]
Nov 03 19:05:34 13b8587 resin-supervisor[5200]: [error]         at /usr/src/app/src/device-state.ts:808:10
Nov 03 19:05:34 13b8587 resin-supervisor[5200]: [api]     POST /v1/restart 503 - 5467.307 ms
```

**Comment by 20k-ultra** [comment]
Since the release is stopped and started it does technically restart the services but it's not the right way obviously.

**Comment by 20k-ultra** [comment]
I experienced this again when release testing (expected since we didn't fix it) but I also go this error when using the Purge Data action which uses `/v1/purge`.

![image](https://user-images.githubusercontent.com/3946250/99439381-18946e00-28e3-11eb-824e-49fb56714cf0.png)

**Comment by 20k-ultra** [comment]
The error for /v1/purge and /v1/restart go to https://github.com/balena-io/balena-supervisor/blob/master/src/device-api/common.js. 

I think if we convert this file to TS it will be more obvious what the issue is because the way it's written now is hard to follow.
