### ISSUE TITLE
Field META_BALENA_VERSION is not available in OS information file: /mnt/root/etc/os-release

### ISSUE THREAD

**Issue by gelbal** [balena-io/balena-supervisor#1543]
Seems like there is a compatibility issue between Resin OS 2.12.7+rev2 and supervisor version 11.14.0 as wee see the following supervisor log when the device is asking for delta update:
> Field META_BALENA_VERSION is not available in OS information file: /mnt/root/etc/os-release

User's device running Resin OS 2.12.7+rev2 and supervisor version 11.14.0 shows the following logs while downloading a delta application update:
```
[[35mdebug[39m]   delta([main] registry2.balena-cloud.com/v2/55b3317ce5c51ea69eeb989c9370f1b2@sha256:97e24176f44d851604c7ff64eb2c1b56c238fe15d869e0140ddba00bdc0a8f4a): Starting delta to registry2.balena-cloud.com/v2/6aa6adc717c61ec693617203022cbd00@sha256:dbfb64ccdee26126b077e92151e23a2766817b691d568511db378917c825eee5
[[35mdebug[39m]   delta([main] registry2.balena-cloud.com/v2/55b3317ce5c51ea69eeb989c9370f1b2@sha256:97e24176f44d851604c7ff64eb2c1b56c238fe15d869e0140ddba00bdc0a8f4a): Applying rsync delta...
[[35mdebug[39m]   delta([main] registry2.balena-cloud.com/v2/55b3317ce5c51ea69eeb989c9370f1b2@sha256:97e24176f44d851604c7ff64eb2c1b56c238fe15d869e0140ddba00bdc0a8f4a): Extracted image config
[[35mdebug[39m]   delta([main] registry2.balena-cloud.com/v2/55b3317ce5c51ea69eeb989c9370f1b2@sha256:97e24176f44d851604c7ff64eb2c1b56c238fe15d869e0140ddba00bdc0a8f4a): Created empty image 7d6728d1e9d767e52a965db5fee5b3073284321d103bd577affd51d048befa4d
[[35mdebug[39m]   delta([main] registry2.balena-cloud.com/v2/55b3317ce5c51ea69eeb989c9370f1b2@sha256:97e24176f44d851604c7ff64eb2c1b56c238fe15d869e0140ddba00bdc0a8f4a): Error: Error: rsync exited. code: 1 signal: null
[[35mdebug[39m]   delta([main] registry2.balena-cloud.com/v2/55b3317ce5c51ea69eeb989c9370f1b2@sha256:97e24176f44d851604c7ff64eb2c1b56c238fe15d869e0140ddba00bdc0a8f4a): Delta stream emitted error: Error: rsync exited. code: 1 signal: null
[[35mdebug[39m]   delta([main] registry2.balena-cloud.com/v2/55b3317ce5c51ea69eeb989c9370f1b2@sha256:97e24176f44d851604c7ff64eb2c1b56c238fe15d869e0140ddba00bdc0a8f4a): Delta failed with Error: rsync exited. code: 1 signal: null
[[36mevent[39m]   Event: Image download error {"error":{"message":"rsync exited. code: 1 signal: null","stack":"Error: rsync exited. code: 1 signal: null\n    at ChildProcess.handleExit (/usr/src/app/dist/app.js:2:826585)\n    at ChildProcess.emit (events.js:322:22)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)"},"image":{"name":"registry2.balena-cloud.com/v2/6aa6adc717c61ec693617203022cbd00@sha256:dbfb64ccdee26126b077e92151e23a2766817b691d568511db378917c825eee5","appId":1098852,"serviceId":142208,"serviceName":"main","imageId":3040203,"releaseId":1624684,"dependent":0,"dockerImageId":null}}
[[33mwarn[39m]    Field META_BALENA_VERSION is not available in OS information file: /mnt/root/etc/os-release
[[33mwarn[39m]    Field META_BALENA_VERSION is not available in OS information file: /mnt/root/etc/os-release
```

**Comment by gelbal** [comment]
As seen on [this JF thread](https://jel.ly.fish/35a8f99d-eab6-4e8b-be8e-df2bd0349131) and investigated on [this FD thread](https://www.flowdock.com/app/rulemotion/resin-tech/threads/2dz0u3JkoDGXpaHyuO0_piF072C), Matt proposed this incompatibility issue as the root cause.

**Comment by 20k-ultra** [comment]
This isn't a bug, the log is just saying that the environment variable the Supervisor was looking for is not available.
